/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdministracionEventos_Interfaz;

import GestorUsuarios.UsuariosInfo;
import java.util.ArrayList;
import javaticket.MenuPrincipal;
import javax.swing.JOptionPane;

/**
 *
 * @author jenniferbueso
 */
public class AdministracionEventos extends javax.swing.JFrame {
    private UsuariosInfo usuarioLogueado;
    
    public AdministracionEventos(UsuariosInfo usuarioLogueado) {
        this.usuarioLogueado = usuarioLogueado;
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonVer = new javax.swing.JLabel();
        BotonRegresar = new javax.swing.JLabel();
        BotonEditar = new javax.swing.JLabel();
        BotonCrear = new javax.swing.JLabel();
        BotonEliminar = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonVer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonVerMouseClicked(evt);
            }
        });
        jPanel1.add(BotonVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 170, 150));

        BotonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseClicked(evt);
            }
        });
        jPanel1.add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, 60, 60));

        BotonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonEditarMouseClicked(evt);
            }
        });
        jPanel1.add(BotonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 170, 150));

        BotonCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCrearMouseClicked(evt);
            }
        });
        jPanel1.add(BotonCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 170, 150));

        BotonEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonEliminarMouseClicked(evt);
            }
        });
        jPanel1.add(BotonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 170, 150));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/administrarEventos.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEditarMouseClicked
        String clase = usuarioLogueado.getClass().getName();
        
        if (clase.equals("GestorUsuarios.Limitado")) {
            JOptionPane.showMessageDialog(null, "Lo siento, esta opción no está disponible para usuarios LIMITADOS.", "Acceso Denegado", JOptionPane.ERROR_MESSAGE);
        } else {
            EditarEvento editarEvento = new EditarEvento(usuarioLogueado);
            editarEvento.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_BotonEditarMouseClicked

    private void BotonVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVerMouseClicked
        VerEvento verEvento = new VerEvento(usuarioLogueado);
        verEvento.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonVerMouseClicked

    private void BotonRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseClicked
        MenuPrincipal menuPrincipal = new MenuPrincipal(usuarioLogueado);
        menuPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonRegresarMouseClicked

    private void BotonEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEliminarMouseClicked
        EliminarEvento eliminarEvento = new EliminarEvento(usuarioLogueado);
        eliminarEvento.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonEliminarMouseClicked

    private void BotonCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCrearMouseClicked
        String clase = usuarioLogueado.getClass().getName();
        
        if (clase.equals("GestorUsuarios.Limitado")) {
            JOptionPane.showMessageDialog(null, "Lo siento, esta opción no está disponible para usuarios LIMITADOS.", "Acceso Denegado", JOptionPane.ERROR_MESSAGE);
        } else {
            CrearEvento crearEvento = new CrearEvento(usuarioLogueado);
            crearEvento.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_BotonCrearMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministracionEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministracionEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministracionEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministracionEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministracionEventos(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BotonCrear;
    private javax.swing.JLabel BotonEditar;
    private javax.swing.JLabel BotonEliminar;
    private javax.swing.JLabel BotonRegresar;
    private javax.swing.JLabel BotonVer;
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
