/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaticket;

import GestorUsuarios.UsuariosInfo;
import java.util.ArrayList;

/**
 *
 * @author jenniferbueso
 */
public class EventosRealizados extends javax.swing.JFrame {
    ArrayList<UsuariosInfo> listaUsuarios;
    private String nombreLabel;
    private UsuariosInfo usuarioLogueado;
   
    public EventosRealizados(ArrayList<UsuariosInfo> listaUsuariosExterna, String nombreLabel, UsuariosInfo usuarioLogueado) {
        listaUsuarios = listaUsuariosExterna;
        this.nombreLabel = nombreLabel;
        this.usuarioLogueado = usuarioLogueado;
        
        initComponents();
        
        EventosArea.setText(Main_JavaTicket.gestionarEventos.buscarEventosRealizados());
        DeportivoLabel.setText(String.valueOf(Main_JavaTicket.gestionarEventos.contadorDeportivoRealizado()));
        MusicalLabel.setText(String.valueOf(Main_JavaTicket.gestionarEventos.contadorMusicalRealizado()));
        ReligiosoLabel.setText(String.valueOf(Main_JavaTicket.gestionarEventos.contadorReligiosoRealizado()));
        
        MontoGeneradoLabel.setText("Lps. " + String.valueOf(Main_JavaTicket.gestionarEventos.montoGeneradoRealizado()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EventosArea = new javax.swing.JTextArea();
        MontoGeneradoLabel = new javax.swing.JLabel();
        ReligiosoLabel = new javax.swing.JLabel();
        MusicalLabel = new javax.swing.JLabel();
        DeportivoLabel = new javax.swing.JLabel();
        BotonRegresar = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);

        EventosArea.setEditable(false);
        EventosArea.setBackground(new java.awt.Color(253, 228, 240));
        EventosArea.setColumns(20);
        EventosArea.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        EventosArea.setForeground(new java.awt.Color(0, 0, 0));
        EventosArea.setRows(5);
        EventosArea.setText("No hay eventos realizados aún.");
        jScrollPane1.setViewportView(EventosArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 360, 270));

        MontoGeneradoLabel.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        MontoGeneradoLabel.setForeground(new java.awt.Color(0, 0, 0));
        MontoGeneradoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MontoGeneradoLabel.setText("Lps. 0.00");
        jPanel1.add(MontoGeneradoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 492, 220, 30));

        ReligiosoLabel.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        ReligiosoLabel.setForeground(new java.awt.Color(0, 0, 0));
        ReligiosoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReligiosoLabel.setText("0");
        jPanel1.add(ReligiosoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 376, 140, 40));

        MusicalLabel.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        MusicalLabel.setForeground(new java.awt.Color(0, 0, 0));
        MusicalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MusicalLabel.setText("0");
        jPanel1.add(MusicalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 303, 140, 40));

        DeportivoLabel.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        DeportivoLabel.setForeground(new java.awt.Color(0, 0, 0));
        DeportivoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DeportivoLabel.setText("0");
        jPanel1.add(DeportivoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 227, 140, 40));

        BotonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseClicked(evt);
            }
        });
        jPanel1.add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, 50, 60));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/EventosRealizados.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseClicked
        Reportes reportes = new Reportes(listaUsuarios, nombreLabel, usuarioLogueado);
        reportes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonRegresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventosRealizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventosRealizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventosRealizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventosRealizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventosRealizados(null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BotonRegresar;
    private javax.swing.JLabel DeportivoLabel;
    private javax.swing.JTextArea EventosArea;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel MontoGeneradoLabel;
    private javax.swing.JLabel MusicalLabel;
    private javax.swing.JLabel ReligiosoLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
