/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaticket;

import GestorEventos.DeportesTipo;
import GestorEventos.EventoDeportivo;
import GestorEventos.EventoMusical;
import GestorEventos.EventoReligioso;
import GestorEventos.EventosInfo;
import GestorEventos.MusicalTipo;
import GestorUsuarios.UsuariosInfo;
import GestorEventos.GestionarEventos;
import GestorUsuarios.Administrador;
import GestorUsuarios.Contenidos;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jenniferbueso
 */
public class VerEvento extends javax.swing.JFrame {
    private ArrayList<UsuariosInfo> listaUsuarios;
    private String nombreLabel, fechaReservada, tipoEvento, panelActual, codigo, titulo, descripcion, rentaS, fechaS;
    private double renta;
    private Date fecha;
    private UsuariosInfo usuarioLogueado;
    private EventosInfo eventoBuscado;
    private EventoDeportivo eventoDeportivo;
    private EventoMusical eventoMusical;
    private EventoReligioso eventoReligioso;
    
    public VerEvento(ArrayList<UsuariosInfo> listaUsuariosExterna, String nombreLabel, UsuariosInfo usuarioLogueado) {
        listaUsuarios = listaUsuariosExterna;
        this.nombreLabel = nombreLabel;
        this.usuarioLogueado = usuarioLogueado;
        
        initComponents();
        
        InicioPanel.setVisible(true);
        DeportePanel.setVisible(false);
        MusicalPanel.setVisible(false);
        ReligiosoPanel.setVisible(false);
        ReligiosoAdicionalPanel.setVisible(false);
        DeporteAdicionalPanel.setVisible(false);
        MusicalAdicionalPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CodigoField = new javax.swing.JTextField();
        FechaField = new javax.swing.JTextField();
        RentaField = new javax.swing.JTextField();
        RentaField1 = new javax.swing.JTextField();
        TituloField = new javax.swing.JTextField();
        TipoEventoField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        DescripcionField = new javax.swing.JTextArea();
        DeporteAdicionalPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        EquipoDosArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        EquipoUnoArea = new javax.swing.JTextArea();
        EquipoDosLabel = new javax.swing.JLabel();
        EquipoUnoLabel = new javax.swing.JLabel();
        FondoDeporteAdicional = new javax.swing.JLabel();
        ReligiosoAdicionalPanel = new javax.swing.JPanel();
        PersonasConvertidasField = new javax.swing.JTextField();
        FondoAdicionalReligioso = new javax.swing.JLabel();
        ReligiosoPanel = new javax.swing.JPanel();
        SeguroFieldR = new javax.swing.JTextField();
        AforoFieldR = new javax.swing.JTextField();
        FondoReligioso = new javax.swing.JLabel();
        DeportePanel = new javax.swing.JPanel();
        TipoDeporteBox = new javax.swing.JComboBox<>(DeportesTipo.values());
        AforoFieldD = new javax.swing.JTextField();
        EquipoDosField = new javax.swing.JTextField();
        EquipoUnoField = new javax.swing.JTextField();
        FondoDeportivo = new javax.swing.JLabel();
        MusicalPanel = new javax.swing.JPanel();
        TipoMusicalBox = new javax.swing.JComboBox<>(MusicalTipo.values());
        SeguroFieldM = new javax.swing.JTextField();
        AforoFieldM = new javax.swing.JTextField();
        FondoMusical = new javax.swing.JLabel();
        MusicalAdicionalPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        CargoField = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        MusicosField = new javax.swing.JTextArea();
        FondoMusicalAdicional = new javax.swing.JLabel();
        InicioPanel = new javax.swing.JPanel();
        FondoInicio = new javax.swing.JLabel();
        BotonRegresar = new javax.swing.JLabel();
        BotonCalendario = new javax.swing.JLabel();
        PagadoLabel = new javax.swing.JLabel();
        CanceladoLabel = new javax.swing.JLabel();
        BotonDatosAdicionales = new javax.swing.JLabel();
        BotonBuscar = new javax.swing.JLabel();
        BotonDatosLabel = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CodigoField.setEditable(false);
        CodigoField.setBackground(new java.awt.Color(253, 228, 240));
        CodigoField.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        CodigoField.setForeground(new java.awt.Color(0, 0, 0));
        CodigoField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CodigoField.setBorder(null);
        CodigoField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CodigoField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CodigoFieldMouseClicked(evt);
            }
        });
        CodigoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoFieldActionPerformed(evt);
            }
        });
        CodigoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CodigoFieldKeyTyped(evt);
            }
        });
        jPanel1.add(CodigoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 193, 260, 40));

        FechaField.setEditable(false);
        FechaField.setBackground(new java.awt.Color(253, 228, 240));
        FechaField.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        FechaField.setForeground(new java.awt.Color(0, 0, 0));
        FechaField.setBorder(null);
        FechaField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FechaField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FechaFieldMouseClicked(evt);
            }
        });
        FechaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaFieldActionPerformed(evt);
            }
        });
        FechaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FechaFieldKeyTyped(evt);
            }
        });
        jPanel1.add(FechaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 483, 300, 40));

        RentaField.setEditable(false);
        RentaField.setBackground(new java.awt.Color(253, 228, 240));
        RentaField.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        RentaField.setForeground(new java.awt.Color(0, 0, 0));
        RentaField.setBorder(null);
        RentaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentaFieldActionPerformed(evt);
            }
        });
        RentaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RentaFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RentaFieldKeyTyped(evt);
            }
        });
        jPanel1.add(RentaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 481, 220, 40));

        RentaField1.setEditable(false);
        RentaField1.setBackground(new java.awt.Color(253, 228, 240));
        RentaField1.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        RentaField1.setForeground(new java.awt.Color(0, 0, 0));
        RentaField1.setText("Lps.");
        RentaField1.setBorder(null);
        RentaField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentaField1ActionPerformed(evt);
            }
        });
        RentaField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RentaField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RentaField1KeyTyped(evt);
            }
        });
        jPanel1.add(RentaField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 481, 40, 40));

        TituloField.setEditable(false);
        TituloField.setBackground(new java.awt.Color(253, 228, 240));
        TituloField.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        TituloField.setForeground(new java.awt.Color(0, 0, 0));
        TituloField.setBorder(null);
        jPanel1.add(TituloField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 387, 260, 40));

        TipoEventoField.setEditable(false);
        TipoEventoField.setBackground(new java.awt.Color(253, 228, 240));
        TipoEventoField.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        TipoEventoField.setForeground(new java.awt.Color(0, 0, 0));
        TipoEventoField.setBorder(null);
        jPanel1.add(TipoEventoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 298, 260, 40));

        jScrollPane1.setBorder(null);

        DescripcionField.setEditable(false);
        DescripcionField.setBackground(new java.awt.Color(253, 228, 240));
        DescripcionField.setColumns(20);
        DescripcionField.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        DescripcionField.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionField.setLineWrap(true);
        DescripcionField.setRows(5);
        jScrollPane1.setViewportView(DescripcionField);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 313, 370, 110));

        DeporteAdicionalPanel.setBackground(new java.awt.Color(255, 255, 255));
        DeporteAdicionalPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setBorder(null);

        EquipoDosArea.setEditable(false);
        EquipoDosArea.setBackground(new java.awt.Color(253, 228, 240));
        EquipoDosArea.setColumns(20);
        EquipoDosArea.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        EquipoDosArea.setForeground(new java.awt.Color(0, 0, 0));
        EquipoDosArea.setRows(5);
        EquipoDosArea.setSize(new java.awt.Dimension(232, 89));
        jScrollPane3.setViewportView(EquipoDosArea);

        DeporteAdicionalPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 54, 360, 90));

        jScrollPane2.setBorder(null);

        EquipoUnoArea.setEditable(false);
        EquipoUnoArea.setBackground(new java.awt.Color(253, 228, 240));
        EquipoUnoArea.setColumns(20);
        EquipoUnoArea.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        EquipoUnoArea.setForeground(new java.awt.Color(0, 0, 0));
        EquipoUnoArea.setRows(5);
        jScrollPane2.setViewportView(EquipoUnoArea);

        DeporteAdicionalPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 54, 360, 90));

        EquipoDosLabel.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        EquipoDosLabel.setForeground(new java.awt.Color(0, 0, 0));
        EquipoDosLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DeporteAdicionalPanel.add(EquipoDosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 370, 30));

        EquipoUnoLabel.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        EquipoUnoLabel.setForeground(new java.awt.Color(0, 0, 0));
        EquipoUnoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DeporteAdicionalPanel.add(EquipoUnoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 360, 30));

        FondoDeporteAdicional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/InterfazDeporteAdicional.png"))); // NOI18N
        DeporteAdicionalPanel.add(FondoDeporteAdicional, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(DeporteAdicionalPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 540, 870, 170));

        ReligiosoAdicionalPanel.setBackground(new java.awt.Color(255, 255, 255));
        ReligiosoAdicionalPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PersonasConvertidasField.setEditable(false);
        PersonasConvertidasField.setBackground(new java.awt.Color(253, 228, 240));
        PersonasConvertidasField.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        PersonasConvertidasField.setForeground(new java.awt.Color(0, 0, 0));
        PersonasConvertidasField.setBorder(null);
        PersonasConvertidasField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PersonasConvertidasFieldKeyTyped(evt);
            }
        });
        ReligiosoAdicionalPanel.add(PersonasConvertidasField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 89, 330, 40));

        FondoAdicionalReligioso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/InterfazReligiosoAdicional.png"))); // NOI18N
        ReligiosoAdicionalPanel.add(FondoAdicionalReligioso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(ReligiosoAdicionalPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 540, 870, 170));

        ReligiosoPanel.setBackground(new java.awt.Color(255, 255, 255));
        ReligiosoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SeguroFieldR.setEditable(false);
        SeguroFieldR.setBackground(new java.awt.Color(253, 228, 240));
        SeguroFieldR.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        SeguroFieldR.setForeground(new java.awt.Color(0, 0, 0));
        SeguroFieldR.setBorder(null);
        SeguroFieldR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SeguroFieldRMouseClicked(evt);
            }
        });
        SeguroFieldR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SeguroFieldRKeyTyped(evt);
            }
        });
        ReligiosoPanel.add(SeguroFieldR, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 65, 270, 40));

        AforoFieldR.setEditable(false);
        AforoFieldR.setBackground(new java.awt.Color(253, 228, 240));
        AforoFieldR.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        AforoFieldR.setForeground(new java.awt.Color(0, 0, 0));
        AforoFieldR.setBorder(null);
        AforoFieldR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AforoFieldRKeyTyped(evt);
            }
        });
        ReligiosoPanel.add(AforoFieldR, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 65, 270, 40));

        FondoReligioso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/InterfazReligioso.png"))); // NOI18N
        ReligiosoPanel.add(FondoReligioso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(ReligiosoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 540, 870, 170));

        DeportePanel.setBackground(new java.awt.Color(255, 255, 255));
        DeportePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TipoDeporteBox.setBackground(new java.awt.Color(253, 228, 240));
        TipoDeporteBox.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        TipoDeporteBox.setForeground(new java.awt.Color(0, 0, 0));
        TipoDeporteBox.setAutoscrolls(true);
        TipoDeporteBox.setBorder(null);
        DeportePanel.add(TipoDeporteBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 109, 170, 40));

        AforoFieldD.setEditable(false);
        AforoFieldD.setBackground(new java.awt.Color(253, 228, 240));
        AforoFieldD.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        AforoFieldD.setForeground(new java.awt.Color(0, 0, 0));
        AforoFieldD.setBorder(null);
        AforoFieldD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AforoFieldDKeyTyped(evt);
            }
        });
        DeportePanel.add(AforoFieldD, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 22, 260, 40));

        EquipoDosField.setEditable(false);
        EquipoDosField.setBackground(new java.awt.Color(253, 228, 240));
        EquipoDosField.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        EquipoDosField.setForeground(new java.awt.Color(0, 0, 0));
        EquipoDosField.setBorder(null);
        DeportePanel.add(EquipoDosField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 109, 260, 40));

        EquipoUnoField.setEditable(false);
        EquipoUnoField.setBackground(new java.awt.Color(253, 228, 240));
        EquipoUnoField.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        EquipoUnoField.setForeground(new java.awt.Color(0, 0, 0));
        EquipoUnoField.setBorder(null);
        DeportePanel.add(EquipoUnoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 22, 260, 40));

        FondoDeportivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/InterfazDeporte.png"))); // NOI18N
        DeportePanel.add(FondoDeportivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(DeportePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 540, 870, 170));

        MusicalPanel.setBackground(new java.awt.Color(255, 255, 255));
        MusicalPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TipoMusicalBox.setBackground(new java.awt.Color(253, 228, 240));
        TipoMusicalBox.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        TipoMusicalBox.setForeground(new java.awt.Color(0, 0, 0));
        TipoMusicalBox.setBorder(null);
        MusicalPanel.add(TipoMusicalBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 26, 170, 40));

        SeguroFieldM.setEditable(false);
        SeguroFieldM.setBackground(new java.awt.Color(253, 228, 240));
        SeguroFieldM.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        SeguroFieldM.setForeground(new java.awt.Color(0, 0, 0));
        SeguroFieldM.setBorder(null);
        SeguroFieldM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeguroFieldMActionPerformed(evt);
            }
        });
        SeguroFieldM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SeguroFieldMKeyTyped(evt);
            }
        });
        MusicalPanel.add(SeguroFieldM, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 105, 270, 40));

        AforoFieldM.setEditable(false);
        AforoFieldM.setBackground(new java.awt.Color(253, 228, 240));
        AforoFieldM.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        AforoFieldM.setForeground(new java.awt.Color(0, 0, 0));
        AforoFieldM.setBorder(null);
        AforoFieldM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AforoFieldMKeyTyped(evt);
            }
        });
        MusicalPanel.add(AforoFieldM, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 26, 270, 40));

        FondoMusical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/InterfazMusical.png"))); // NOI18N
        MusicalPanel.add(FondoMusical, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(MusicalPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 540, 870, 170));

        MusicalAdicionalPanel.setBackground(new java.awt.Color(255, 255, 255));
        MusicalAdicionalPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane4.setBorder(null);

        CargoField.setEditable(false);
        CargoField.setBackground(new java.awt.Color(253, 228, 240));
        CargoField.setColumns(20);
        CargoField.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        CargoField.setForeground(new java.awt.Color(0, 0, 0));
        CargoField.setRows(5);
        CargoField.setSize(new java.awt.Dimension(232, 89));
        jScrollPane4.setViewportView(CargoField);

        MusicalAdicionalPanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 54, 360, 90));

        jScrollPane5.setBorder(null);

        MusicosField.setEditable(false);
        MusicosField.setBackground(new java.awt.Color(253, 228, 240));
        MusicosField.setColumns(20);
        MusicosField.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        MusicosField.setForeground(new java.awt.Color(0, 0, 0));
        MusicosField.setRows(5);
        jScrollPane5.setViewportView(MusicosField);

        MusicalAdicionalPanel.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 54, 360, 90));

        FondoMusicalAdicional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/InterfazMusicalAdicional.png"))); // NOI18N
        MusicalAdicionalPanel.add(FondoMusicalAdicional, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(MusicalAdicionalPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 540, 870, 170));

        InicioPanel.setBackground(new java.awt.Color(255, 255, 255));
        InicioPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/InterfazInicioEditar.png"))); // NOI18N
        InicioPanel.add(FondoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(InicioPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 540, 870, 170));

        BotonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseClicked(evt);
            }
        });
        jPanel1.add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 120, 60, 50));

        BotonCalendario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCalendario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCalendarioMouseClicked(evt);
            }
        });
        jPanel1.add(BotonCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 480, 60, 50));

        PagadoLabel.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        PagadoLabel.setForeground(new java.awt.Color(0, 0, 0));
        PagadoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(PagadoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 726, 170, 30));

        CanceladoLabel.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        CanceladoLabel.setForeground(new java.awt.Color(0, 0, 0));
        CanceladoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(CanceladoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 726, 170, 30));

        BotonDatosAdicionales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonDatosAdicionales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonDatosAdicionalesMouseClicked(evt);
            }
        });
        jPanel1.add(BotonDatosAdicionales, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 723, 140, 30));

        BotonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonBuscarMouseClicked(evt);
            }
        });
        jPanel1.add(BotonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 50, 50));

        BotonDatosLabel.setFont(new java.awt.Font("Avenir Next Condensed", 1, 14)); // NOI18N
        BotonDatosLabel.setForeground(new java.awt.Color(0, 0, 0));
        BotonDatosLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BotonDatosLabel.setText("Datos Adicionales");
        jPanel1.add(BotonDatosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 730, 120, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/VerEvento.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AforoFieldDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AforoFieldDKeyTyped
    }//GEN-LAST:event_AforoFieldDKeyTyped

    private void RentaFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RentaFieldKeyTyped
    }//GEN-LAST:event_RentaFieldKeyTyped

    public void updateFechaReservada(String fecha) {
    }
    
    private void AforoFieldMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AforoFieldMKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_AforoFieldMKeyTyped

    private void SeguroFieldMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SeguroFieldMKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_SeguroFieldMKeyTyped

    private void SeguroFieldRKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SeguroFieldRKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_SeguroFieldRKeyTyped

    private void AforoFieldRKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AforoFieldRKeyTyped
        int tecla = evt.getKeyChar();
        boolean valido = tecla >= 48 && tecla <= 57;

        if(!valido){
            evt.consume();
        }
    }//GEN-LAST:event_AforoFieldRKeyTyped

    private void BotonRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseClicked
        AdministracionEventos administracionEventos = new AdministracionEventos(listaUsuarios, nombreLabel, usuarioLogueado);
        administracionEventos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonRegresarMouseClicked
    
    private void datosGeneralesSet() {
        titulo = TituloField.getText();
        descripcion = DescripcionField.getText();
        rentaS = RentaField.getText();
        fechaS = FechaField.getText();
        
        if (titulo.isEmpty() || titulo.isBlank()) {
            JOptionPane.showMessageDialog(null, "Completa el campo de Título.", "Campo Incompleto", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (descripcion.isEmpty() || descripcion.isBlank()) {
            JOptionPane.showMessageDialog(null, "Completa el campo de Descripción.", "Campo Incompleto", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (fechaS.isEmpty() || fechaS.isBlank()) {
            JOptionPane.showMessageDialog(null, "Completa el campo de Fecha.", "Campo Incompleto", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (rentaS.isEmpty() || rentaS.isBlank()) {
            JOptionPane.showMessageDialog(null, "Completa el campo de Renta.", "Campo Incompleto", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        renta = Double.parseDouble(rentaS);
        eventoBuscado.setTitulo(titulo);
        eventoBuscado.setDescripcion(descripcion);
        eventoBuscado.setMontoRenta(renta);
        eventoBuscado.setFecha(fecha);
        System.out.println("fecha general: " + fecha);
    }
    
    private void agregarIdAlUsuario(String id) {
	if (usuarioLogueado instanceof Administrador) {
            ((Administrador) usuarioLogueado).agregarIdEvento(id);
        } else {
            ((Contenidos) usuarioLogueado).agregarIdEvento(id);
        }
    }
    
    private void BotonCalendarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCalendarioMouseClicked
        CalendarioVisual calendarioVisual = new CalendarioVisual();
        calendarioVisual.setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_BotonCalendarioMouseClicked

    private void FechaFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FechaFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaFieldKeyTyped

    private void FechaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaFieldActionPerformed
    }//GEN-LAST:event_FechaFieldActionPerformed

    private void FechaFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FechaFieldMouseClicked
        JOptionPane.showMessageDialog(null, "Si deseas reservar una fecha, por favor haz clic en el ícono del calendario.", "Información de Reserva", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_FechaFieldMouseClicked

    private void SeguroFieldMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeguroFieldMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeguroFieldMActionPerformed

    private void RentaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RentaFieldActionPerformed

    private void RentaFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RentaFieldKeyReleased
    }//GEN-LAST:event_RentaFieldKeyReleased

    private void RentaField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentaField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RentaField1ActionPerformed

    private void RentaField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RentaField1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_RentaField1KeyReleased

    private void RentaField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RentaField1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_RentaField1KeyTyped

    private void CodigoFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CodigoFieldMouseClicked
        JOptionPane.showMessageDialog(null, "Presiona el ícono a tu derecha para buscar un evento.", "Buscar Evento", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_CodigoFieldMouseClicked

    private void CodigoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoFieldActionPerformed

    private void CodigoFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CodigoFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoFieldKeyTyped

    private void BotonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonBuscarMouseClicked
        codigo = JOptionPane.showInputDialog(null, "Ingrese el código del evento:", "Buscar Evento", JOptionPane.QUESTION_MESSAGE);
        eventoBuscado = Main_JavaTicket.gestionarEventos.regresarEvento(codigo);
        boolean mostrarNoPagado = false;
        
        if (eventoBuscado == null) {
            JOptionPane.showMessageDialog(null, "El evento con el código " + codigo + " no existe.", "Búsqueda Fallida", JOptionPane.ERROR_MESSAGE);
        } else {
            CodigoField.setText(codigo);
            TituloField.setText(eventoBuscado.getTitulo());
            RentaField.setText(String.valueOf(eventoBuscado.getMontoRenta()));
            DescripcionField.setText(eventoBuscado.getDescripcion());
            fecha = eventoBuscado.getFecha();
            
            if (eventoBuscado.isCancelado()) {
                CanceladoLabel.setText("Cancelado");
                
                if (eventoBuscado.isIndemnizacion()) 
                    PagadoLabel.setText("Indemnización");
                PagadoLabel.setText("Sin Indemnización");
            } else {
                CanceladoLabel.setText("Activo");
                mostrarNoPagado = true;
            }
            
            eventoBuscado.verificarSiYaRealizado();
            
            if(eventoBuscado.yaRealizado()) {
                CanceladoLabel.setText("Realizado");
                PagadoLabel.setText("Pagado");
            } else if (mostrarNoPagado){
                PagadoLabel.setText("No Pagado");
            }
            
            SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy", new Locale("es", "ES"));
            String fechaFormateada = formatoFecha.format(eventoBuscado.getFecha());
            FechaField.setText(fechaFormateada);
            
            if (eventoBuscado.getClass().getName().toString().equals("")) {
                TipoEventoField.setText("");
            } else if (eventoBuscado.getClass().getName().toString().equals("GestorEventos.EventoDeportivo")) {
                eventoDeportivo = (EventoDeportivo) eventoBuscado;
                tipoEvento = "Deportivo";
                TipoEventoField.setText("Deportivo");
                panelActual = "DeportivoAdicional";
                
                InicioPanel.setVisible(false);
                DeportePanel.setVisible(true);
                MusicalPanel.setVisible(false);
                ReligiosoPanel.setVisible(false);
                
                EquipoUnoField.setText(eventoDeportivo.getEquipo1());
                EquipoDosField.setText(eventoDeportivo.getEquipo2());
                AforoFieldD.setText(String.valueOf(eventoDeportivo.getAforo()));
                TipoDeporteBox.setSelectedItem(eventoDeportivo.getTipoDeporte());
                
                EquipoUnoLabel.setText(eventoDeportivo.getEquipo1());
                EquipoDosLabel.setText(eventoDeportivo.getEquipo2());
                
                EquipoUnoArea.setText(eventoDeportivo.getJugadores1());
                EquipoDosArea.setText(eventoDeportivo.getJugadores2());
                
            } else if (eventoBuscado.getClass().getName().toString().equals("GestorEventos.EventoMusical")) {
                eventoMusical = (EventoMusical) eventoBuscado;
                tipoEvento = "Musical";
                TipoEventoField.setText("Musical");
                panelActual = "MusicalAdicional";
                
                InicioPanel.setVisible(false);
                DeportePanel.setVisible(false);
                MusicalPanel.setVisible(true);
                ReligiosoPanel.setVisible(false);
                
                AforoFieldM.setText(String.valueOf(eventoMusical.getAforo()));
                TipoMusicalBox.setSelectedItem(eventoMusical.getTipoMusica());
                SeguroFieldM.setText(String.valueOf(eventoMusical.getSeguro()));
                
                MusicosField.setText(eventoMusical.getMusicos());
                CargoField.setText(eventoMusical.getCargos());
                
            } else if (eventoBuscado.getClass().getName().toString().equals("GestorEventos.EventoReligioso")) {
                eventoReligioso = (EventoReligioso) eventoBuscado;
                tipoEvento = "Religioso";
                TipoEventoField.setText("Religioso");
                panelActual = "ReligiosoAdicional";
                
                InicioPanel.setVisible(false);
                DeportePanel.setVisible(false);
                MusicalPanel.setVisible(false);
                ReligiosoPanel.setVisible(true);
                
                AforoFieldR.setText(String.valueOf(eventoReligioso.getAforo()));
                SeguroFieldR.setText("2000");
                
                PersonasConvertidasField.setText(String.valueOf(eventoReligioso.getConvertidos()));
            }
            
        }
        
    }//GEN-LAST:event_BotonBuscarMouseClicked

    private void SeguroFieldRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SeguroFieldRMouseClicked
    }//GEN-LAST:event_SeguroFieldRMouseClicked

    private void PersonasConvertidasFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PersonasConvertidasFieldKeyTyped
        int tecla = evt.getKeyChar();
        boolean valido = tecla >= 48 && tecla <= 57;

        if(!valido){
            evt.consume();
        }
    }//GEN-LAST:event_PersonasConvertidasFieldKeyTyped

    private void BotonDatosAdicionalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonDatosAdicionalesMouseClicked
        if (panelActual == null) {
            JOptionPane.showMessageDialog(null, "Por favor, realiza una búsqueda de evento antes de continuar.", "Función Deshabilitada", JOptionPane.ERROR_MESSAGE);
        } else if (panelActual.equals("ReligiosoAdicional") && tipoEvento.equals("Religioso")) {
            ReligiosoPanel.setVisible(false);
            ReligiosoAdicionalPanel.setVisible(true);
            panelActual = "Religioso";
            BotonDatosLabel.setText("Regresar");
        } else if (panelActual.equals("Religioso") && tipoEvento.equals("Religioso")) {
            ReligiosoPanel.setVisible(true);
            ReligiosoAdicionalPanel.setVisible(false);
            panelActual = "ReligiosoAdicional";
            BotonDatosLabel.setText("Datos Adicionales");
        } else if (panelActual.equals("DeportivoAdicional") && tipoEvento.equals("Deportivo")) {
            DeportePanel.setVisible(false);
            DeporteAdicionalPanel.setVisible(true);
            panelActual = "Deportivo";
            BotonDatosLabel.setText("Regresar");
        } else if (panelActual.equals("Deportivo") && tipoEvento.equals("Deportivo")) {
            DeportePanel.setVisible(true);
            DeporteAdicionalPanel.setVisible(false);
            panelActual = "DeportivoAdicional";
            BotonDatosLabel.setText("Datos Adicionales");
        } else if (panelActual.equals("MusicalAdicional") && tipoEvento.equals("Musical")) {
            MusicalPanel.setVisible(false);
            MusicalAdicionalPanel.setVisible(true);
            panelActual = "Musical";
            BotonDatosLabel.setText("Regresar");
        } else if (panelActual.equals("Musical") && tipoEvento.equals("Musical")) {
            MusicalPanel.setVisible(true);
            MusicalAdicionalPanel.setVisible(false);
            panelActual = "MusicalAdicional";
            BotonDatosLabel.setText("Datos Adicionales");
        }
    }//GEN-LAST:event_BotonDatosAdicionalesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerEvento(null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AforoFieldD;
    private javax.swing.JTextField AforoFieldM;
    private javax.swing.JTextField AforoFieldR;
    private javax.swing.JLabel BotonBuscar;
    private javax.swing.JLabel BotonCalendario;
    private javax.swing.JLabel BotonDatosAdicionales;
    private javax.swing.JLabel BotonDatosLabel;
    private javax.swing.JLabel BotonRegresar;
    private javax.swing.JLabel CanceladoLabel;
    private javax.swing.JTextArea CargoField;
    private javax.swing.JTextField CodigoField;
    private javax.swing.JPanel DeporteAdicionalPanel;
    private javax.swing.JPanel DeportePanel;
    private javax.swing.JTextArea DescripcionField;
    private javax.swing.JTextArea EquipoDosArea;
    private javax.swing.JTextField EquipoDosField;
    private javax.swing.JLabel EquipoDosLabel;
    private javax.swing.JTextArea EquipoUnoArea;
    private javax.swing.JTextField EquipoUnoField;
    private javax.swing.JLabel EquipoUnoLabel;
    private javax.swing.JTextField FechaField;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel FondoAdicionalReligioso;
    private javax.swing.JLabel FondoDeporteAdicional;
    private javax.swing.JLabel FondoDeportivo;
    private javax.swing.JLabel FondoInicio;
    private javax.swing.JLabel FondoMusical;
    private javax.swing.JLabel FondoMusicalAdicional;
    private javax.swing.JLabel FondoReligioso;
    private javax.swing.JPanel InicioPanel;
    private javax.swing.JPanel MusicalAdicionalPanel;
    private javax.swing.JPanel MusicalPanel;
    private javax.swing.JTextArea MusicosField;
    private javax.swing.JLabel PagadoLabel;
    private javax.swing.JTextField PersonasConvertidasField;
    private javax.swing.JPanel ReligiosoAdicionalPanel;
    private javax.swing.JPanel ReligiosoPanel;
    private javax.swing.JTextField RentaField;
    private javax.swing.JTextField RentaField1;
    private javax.swing.JTextField SeguroFieldM;
    private javax.swing.JTextField SeguroFieldR;
    private javax.swing.JComboBox<DeportesTipo> TipoDeporteBox;
    private javax.swing.JTextField TipoEventoField;
    private javax.swing.JComboBox<MusicalTipo> TipoMusicalBox;
    private javax.swing.JTextField TituloField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
