/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Reportes_Interfaz;

import GestorUsuarios.UsuariosInfo;
import GraficosReportes.GraficoEventos;
import javaticket.Main_JavaTicket;

/**
 *
 * @author jenniferbueso
 */
public class EventosCancelados extends javax.swing.JFrame {
    private UsuariosInfo usuarioLogueado;
    
    public EventosCancelados(UsuariosInfo usuarioLogueado) {
        this.usuarioLogueado = usuarioLogueado;
        
        initComponents();
        
        EventosArea.setText(Main_JavaTicket.contadoresReportes.buscarEventosCancelados());
        DeportivoLabel.setText(String.valueOf(Main_JavaTicket.contadoresReportes.contadorDeportivoCancelado()));
        MusicalLabel.setText(String.valueOf(Main_JavaTicket.contadoresReportes.contadorMusicalCancelado()));
        ReligiosoLabel.setText(String.valueOf(Main_JavaTicket.contadoresReportes.contadorReligiosoCancelado()));
        MultaTotalLabel.setText("Lps. " + String.valueOf(Main_JavaTicket.contadoresReportes.MultaGenerada()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EventosArea = new javax.swing.JTextArea();
        MultaTotalLabel = new javax.swing.JLabel();
        ReligiosoLabel = new javax.swing.JLabel();
        MusicalLabel = new javax.swing.JLabel();
        DeportivoLabel = new javax.swing.JLabel();
        BotonRegresar1 = new javax.swing.JLabel();
        BotonGrafico = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);

        EventosArea.setEditable(false);
        EventosArea.setBackground(new java.awt.Color(253, 228, 240));
        EventosArea.setColumns(20);
        EventosArea.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        EventosArea.setForeground(new java.awt.Color(0, 0, 0));
        EventosArea.setRows(5);
        EventosArea.setText("No hay eventos cancelados aún.");
        jScrollPane1.setViewportView(EventosArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 360, 270));

        MultaTotalLabel.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        MultaTotalLabel.setForeground(new java.awt.Color(0, 0, 0));
        MultaTotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MultaTotalLabel.setText("Lps. 0.00");
        jPanel1.add(MultaTotalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 492, 220, 30));

        ReligiosoLabel.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        ReligiosoLabel.setForeground(new java.awt.Color(0, 0, 0));
        ReligiosoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReligiosoLabel.setText("0");
        jPanel1.add(ReligiosoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 376, 140, 40));

        MusicalLabel.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        MusicalLabel.setForeground(new java.awt.Color(0, 0, 0));
        MusicalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MusicalLabel.setText("0");
        jPanel1.add(MusicalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 303, 140, 40));

        DeportivoLabel.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        DeportivoLabel.setForeground(new java.awt.Color(0, 0, 0));
        DeportivoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DeportivoLabel.setText("0");
        jPanel1.add(DeportivoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 227, 140, 40));

        BotonRegresar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRegresar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRegresar1MouseClicked(evt);
            }
        });
        jPanel1.add(BotonRegresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, 50, 60));

        BotonGrafico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonGrafico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonGraficoMouseClicked(evt);
            }
        });
        jPanel1.add(BotonGrafico, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 60, 60));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/EventosCancelados.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegresar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresar1MouseClicked
        Reportes reportes = new Reportes(usuarioLogueado);
        reportes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonRegresar1MouseClicked

    private void BotonGraficoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonGraficoMouseClicked
        Main_JavaTicket.gestionarGraficos.setEventosCancelados(true);
        GraficoEventos graficoEventosRealizados = new GraficoEventos(usuarioLogueado);
        graficoEventosRealizados.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonGraficoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventosCancelados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventosCancelados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventosCancelados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventosCancelados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventosCancelados(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BotonGrafico;
    private javax.swing.JLabel BotonRegresar1;
    private javax.swing.JLabel DeportivoLabel;
    private javax.swing.JTextArea EventosArea;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel MultaTotalLabel;
    private javax.swing.JLabel MusicalLabel;
    private javax.swing.JLabel ReligiosoLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
