/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Reportes_Interfaz;

import Reportes_Interfaz.Reportes;
import GestorEventos.EventoDeportivo;
import GestorEventos.EventoMusical;
import GestorEventos.EventoReligioso;
import GestorEventos.EventosInfo;
import GestorUsuarios.Administrador;
import GestorUsuarios.Contenidos;
import GestorUsuarios.Limitado;
import GestorUsuarios.UsuariosInfo;
import java.util.ArrayList;
import javaticket.Main_JavaTicket;

/**
 *
 * @author jenniferbueso
 */
public class PerfilUsuario extends javax.swing.JFrame {
    private UsuariosInfo usuarioLogueado;
    
    public PerfilUsuario(UsuariosInfo usuarioLogueado) {
        this.usuarioLogueado = usuarioLogueado;
        
        initComponents();
        
        if (usuarioLogueado instanceof Administrador){
            AccesoField.setText("Administador");
        } else if (usuarioLogueado instanceof Limitado){
            AccesoField.setText("Limitado");
        } else if (usuarioLogueado instanceof Contenidos){
            AccesoField.setText("Contenido");
        }
        
        
        NombreField.setText(usuarioLogueado.getNombreCompleto());
        UsuarioField.setText(usuarioLogueado.getUsuario());
        EdadField.setText(Integer.toString(usuarioLogueado.getEdad()));
        ContraField.setText(usuarioLogueado.getContra());
        EventosArea.setText(EventosRealizadosUsuarioLogueado());
    }

    public String EventosRealizadosUsuarioLogueado() {
        StringBuilder eventosRealizados = new StringBuilder();
        ArrayList<String> idEventos;
        String tipo = "", estado = "";
        
        if (usuarioLogueado instanceof Administrador) {
            Administrador usuario = (Administrador) usuarioLogueado;
            idEventos = usuario.getIdEventos();
        } else {
            Contenidos usuario = (Contenidos) usuarioLogueado;
            idEventos = usuario.getIdEventos();
        }
            for (String idEvento : idEventos) {
                EventosInfo evento = Main_JavaTicket.gestionarEventos.buscarEvento(idEvento);
                if (evento != null) {
                    
                    if (evento instanceof EventoDeportivo) {
                        tipo = "Deportivo";
                    } else if (evento instanceof EventoMusical) {
                        tipo = "Musical";
                    } else if (evento instanceof EventoReligioso) {
                        tipo = "Religioso";
                    }
                    
                    if (evento.yaRealizado()) {
                        estado = "Realizado";
                    } if (evento.isCancelado()) {
                        estado = "Cancelado";
                    } else {
                        estado = "Activo";
                    }
                    
                    eventosRealizados.append(evento.getCodigo()).append(" - ").append(tipo).append(" - ").append(evento.getTitulo()).append(" - ").append(estado + " - ").append("Lps. " + String.valueOf(evento.getMontoRenta())).append("\n");
                }
            }
        return eventosRealizados.toString();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EventosArea = new javax.swing.JTextArea();
        ContraField = new javax.swing.JLabel();
        EdadField = new javax.swing.JLabel();
        AccesoField = new javax.swing.JLabel();
        UsuarioField = new javax.swing.JLabel();
        NombreField = new javax.swing.JLabel();
        BotonRegresar2 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);

        EventosArea.setEditable(false);
        EventosArea.setBackground(new java.awt.Color(253, 228, 240));
        EventosArea.setColumns(20);
        EventosArea.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        EventosArea.setForeground(new java.awt.Color(0, 0, 0));
        EventosArea.setRows(5);
        EventosArea.setText("El usuario no ha realizado ningún evento aún.");
        jScrollPane1.setViewportView(EventosArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 280, 350, 230));

        ContraField.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        ContraField.setForeground(new java.awt.Color(0, 0, 0));
        ContraField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(ContraField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 485, 250, 40));

        EdadField.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        EdadField.setForeground(new java.awt.Color(0, 0, 0));
        EdadField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(EdadField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 416, 250, 40));

        AccesoField.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        AccesoField.setForeground(new java.awt.Color(0, 0, 0));
        AccesoField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(AccesoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 342, 250, 40));

        UsuarioField.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        UsuarioField.setForeground(new java.awt.Color(0, 0, 0));
        UsuarioField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(UsuarioField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 267, 250, 40));

        NombreField.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        NombreField.setForeground(new java.awt.Color(0, 0, 0));
        NombreField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(NombreField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 194, 350, 40));

        BotonRegresar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRegresar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRegresar2MouseClicked(evt);
            }
        });
        jPanel1.add(BotonRegresar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, 50, 60));

        Fondo.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        Fondo.setForeground(new java.awt.Color(0, 0, 0));
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/PerfilUsuario.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegresar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresar2MouseClicked
        Reportes reportes = new Reportes(usuarioLogueado);
        reportes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonRegresar2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerfilUsuario(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccesoField;
    private javax.swing.JLabel BotonRegresar2;
    private javax.swing.JLabel ContraField;
    private javax.swing.JLabel EdadField;
    private javax.swing.JTextArea EventosArea;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel NombreField;
    private javax.swing.JLabel UsuarioField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
