/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Reportes_Interfaz;

import GestorUsuarios.UsuariosInfo;
import java.util.ArrayList;
import javaticket.MenuPrincipal;

/**
 *
 * @author jenniferbueso
 */
public class Reportes extends javax.swing.JFrame {
    private UsuariosInfo usuarioLogueado;
   
    public Reportes(UsuariosInfo usuarioLogueado) {
        this.usuarioLogueado = usuarioLogueado;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonEventosFecha = new javax.swing.JLabel();
        BotonEventosCancelados = new javax.swing.JLabel();
        BotonEventosFuturos = new javax.swing.JLabel();
        BotonRegresar = new javax.swing.JLabel();
        BotonEventosRealizados1 = new javax.swing.JLabel();
        BotonVerPerfil = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonEventosFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonEventosFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonEventosFechaMouseClicked(evt);
            }
        });
        jPanel1.add(BotonEventosFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, 170, 160));

        BotonEventosCancelados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonEventosCancelados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonEventosCanceladosMouseClicked(evt);
            }
        });
        jPanel1.add(BotonEventosCancelados, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 170, 160));

        BotonEventosFuturos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonEventosFuturos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonEventosFuturosMouseClicked(evt);
            }
        });
        jPanel1.add(BotonEventosFuturos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 170, 160));

        BotonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseClicked(evt);
            }
        });
        jPanel1.add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 150, 60, 50));

        BotonEventosRealizados1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonEventosRealizados1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonEventosRealizados1MouseClicked(evt);
            }
        });
        jPanel1.add(BotonEventosRealizados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 170, 160));

        BotonVerPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonVerPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonVerPerfilMouseClicked(evt);
            }
        });
        jPanel1.add(BotonVerPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 210, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/Reportes.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseClicked
        MenuPrincipal menuPrincipal = new MenuPrincipal(usuarioLogueado);
        menuPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonRegresarMouseClicked

    private void BotonEventosRealizados1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEventosRealizados1MouseClicked
        EventosRealizados eventosRealizados = new EventosRealizados(usuarioLogueado);
        eventosRealizados.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonEventosRealizados1MouseClicked

    private void BotonVerPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVerPerfilMouseClicked
        PerfilUsuario perfilUsuario = new PerfilUsuario(usuarioLogueado);
        perfilUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonVerPerfilMouseClicked

    private void BotonEventosCanceladosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEventosCanceladosMouseClicked
        EventosCancelados eventosCancelados = new EventosCancelados(usuarioLogueado);
        eventosCancelados.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonEventosCanceladosMouseClicked

    private void BotonEventosFuturosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEventosFuturosMouseClicked
        EventosFuturos eventosFuturos = new EventosFuturos(usuarioLogueado);
        eventosFuturos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonEventosFuturosMouseClicked

    private void BotonEventosFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEventosFechaMouseClicked
        EventosPorFecha eventosPorFecha = new EventosPorFecha(usuarioLogueado);
        eventosPorFecha.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonEventosFechaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BotonEventosCancelados;
    private javax.swing.JLabel BotonEventosFecha;
    private javax.swing.JLabel BotonEventosFuturos;
    private javax.swing.JLabel BotonEventosRealizados1;
    private javax.swing.JLabel BotonRegresar;
    private javax.swing.JLabel BotonVerPerfil;
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
